#!/usr/bin/sh

#################################
# Important!!! For the script to work, 
# delete the -Werror=format-security from /etc/makepkg.conf
#################################
cd 
mkdir ARMLinuxGnueabi

# Install dependencies
sudo pacman -S rsync elfutils glibc zlib libmpc gperf python dejagnu inetutils qemu qemu-arch-extra --noconfirm

gpg --recv-keys 79BE3E4300411886 
gpg --recv-keys 38DBBDC86092693E
gpg --recv-keys 3AB00996FC26A641 
gpg --recv-keys 16792B4EA25340F8



pushd ARMLinuxGnueabi
git clone https://aur.archlinux.org/arm-linux-gnueabihf-linux-api-headers.git

pushd arm-linux-gnueabihf-linux-api-headers  
makepkg -si --noconfirm
popd

git clone https://aur.archlinux.org/arm-linux-gnueabihf-binutils.git

pushd arm-linux-gnueabihf-binutils
makepkg -si --noconfirm
popd

git clone https://aur.archlinux.org/arm-linux-gnueabihf-gcc-stage1.git

pushd arm-linux-gnueabihf-gcc-stage1
makepkg -si --noconfirm
popd

git clone https://aur.archlinux.org/arm-linux-gnueabihf-glibc-headers.git

pushd arm-linux-gnueabihf-glibc-headers
makepkg -si --noconfirm
popd

git clone https://aur.archlinux.org/arm-linux-gnueabihf-gcc-stage2.git

pushd arm-linux-gnueabihf-gcc-stage2
makepkg -si 
popd

git clone https://aur.archlinux.org/arm-linux-gnueabihf-glibc.git

pushd arm-linux-gnueabihf-glibc
makepkg -si
popd

git clone https://aur.archlinux.org/arm-linux-gnueabihf-gcc.git

pushd arm-linux-gnueabihf-gcc
makepkg -si
popd

popd

